name: flutter_demo
description: "Application de communication pour autistes avec sons."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/mal_main.mp3
    - assets/sounds/mal_pied.mp3
    - assets/sounds/soif.mp3
    - assets/sounds/faim.mp3
    - assets/sounds/chips.mp3
